steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "container",
        "clusters",
        "get-credentials",
        "cvs-demo-cluster-1",
        "--zone",
        "us-central1",
      ]
  - name: "gcr.io/cloud-builders/kubectl"
    args: ["apply", "-f", "./confg"]
