apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-depl
  namespace: default
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: gcr.io/kubernetes-346311/back-end-1:latest
